### ISSUE TITLE
Python 3.9 support seems broken

### ISSUE THREAD

**Issue by boutetnico** [untergeek/es_client#60]
When used with `elasticsearch-curator` 8.0.14, I've noticed `es_client` 8.13.0 running on Python 3.9.2 produces the following error:

```
/usr/local/bin/curator --config /etc/curator/curator.yml /etc/curator/actionfile.yml
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 5, in <module>
    from curator.cli import cli
  File "/usr/local/lib/python3.9/dist-packages/curator/__init__.py", line 10, in <module>
    from curator.cli import *
  File "/usr/local/lib/python3.9/dist-packages/curator/cli.py", line 8, in <module>
    from es_client.helpers.logging import configure_logging
  File "/usr/local/lib/python3.9/dist-packages/es_client/helpers/logging.py", line 200, in <module>
    def get_handler(logfile: str | None) -> Union[logging.FileHandler, logging.StreamHandler]:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

A workaround is to add the following in `/usr/local/lib/python3.9/dist-packages/es_client/helpers/logging.py`on line 2:
```python
from __future__ import annotations
```

Not sure if you are still supporting Python 3.9, feel free to close if not, but at least the workaround may help some folks.

**Comment by untergeek** [comment]
Thanks for reporting this. I will address it.

**Comment by untergeek** [comment]
[Curator v8.0.15](https://github.com/elastic/curator/releases/tag/v8.0.15) has the patched version of es_client now. It's already been published to PyPI.

**Comment by boutetnico** [comment]
awesome, it works. thank you!
